# Generated by Django 4.1.13 on 2024-11-13 11:05

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('is_main', models.BooleanField(verbose_name='Является главным каталогом?')),
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название каталога')),
                ('image', models.ImageField(blank=True, upload_to='images_storage', verbose_name='Заглавное изображение каталога')),
                ('description', models.CharField(blank=True, max_length=1000, verbose_name='Описание каталога')),
                ('child', models.ManyToManyField(blank=True, to='categories.catalog', verbose_name='ID вложенных каталогов')),
            ],
            options={
                'verbose_name': 'Каталог темы',
                'verbose_name_plural': 'Темы',
            },
        ),
    ]
