# Generated by Django 4.1.13 on 2024-09-17 12:33

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Catalog',
            fields=[
                ('is_main', models.BooleanField(verbose_name='Является главным каталогом?')),
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100, verbose_name='Название каталога')),
                ('child', models.ManyToManyField(blank=True, to='categories.catalog', verbose_name='ID вложенных каталогов')),
            ],
        ),
    ]
