# Generated by Django 4.1.13 on 2024-09-16 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='catalog',
            name='child',
        ),
        migrations.AddField(
            model_name='catalog',
            name='child',
            field=models.ManyToManyField(blank=True, related_name='childs', to='categories.catalog', verbose_name='ID вложенных каталогов'),
        ),
    ]
