# Generated by Django 4.1.13 on 2024-09-16 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0002_remove_catalog_child_catalog_child'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalog',
            name='child',
            field=models.ManyToManyField(blank=True, to='categories.catalog', verbose_name='ID вложенных каталогов'),
        ),
    ]
