# Generated by Django 4.1.13 on 2024-09-17 06:39

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Описание вопроса')),
            ],
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('questions_list', models.ManyToManyField(to='tests.question')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='answers',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tests.variant', verbose_name='Название каталога'),
        ),
    ]
