# Generated by Django 4.1.13 on 2024-11-13 11:05

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Описание вопроса')),
                ('question_type', models.CharField(choices=[('radio', 'Один правильный ответ'), ('checkbox', 'Несколько правильных ответов'), ('input', 'Ввод текста')], default='checkbox', max_length=50, verbose_name='Тип вопроса')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Вариант ответа',
                'verbose_name_plural': 'Варианты ответа',
            },
        ),
        migrations.CreateModel(
            name='Test',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Название теста')),
                ('catalogs', models.ManyToManyField(blank=True, related_name='tests', to='categories.catalog', verbose_name='Принадлежит каталогам')),
                ('questions_list', models.ManyToManyField(to='tests.question', verbose_name='Список вопросов')),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
            },
        ),
        migrations.CreateModel(
            name='QuestionVariantRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_correct', models.BooleanField(default=False, verbose_name='Является правильным?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='question_id', to='tests.question')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variant_id', to='tests.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Вариант',
                'verbose_name_plural': 'Варианты ответа',
                'db_table': 'question_variants',
            },
        ),
        migrations.AddField(
            model_name='question',
            name='variants',
            field=models.ManyToManyField(related_name='correct_variants', through='tests.QuestionVariantRel', to='tests.variant', verbose_name='Список правильных ответов'),
        ),
    ]
