# Generated by Django 5.1.3 on 2024-12-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='test_photo',
            field=models.ImageField(blank=True, upload_to='tests_storage', verbose_name='Фотография теста'),
        ),
    ]
