# Generated by Django 4.1.13 on 2024-09-17 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_remove_question_answers_question_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='label',
            field=models.CharField(default=123, max_length=50, verbose_name='Название теста'),
            preserve_default=False,
        ),
    ]
