# Generated by Django 5.1.3 on 2025-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0002_test_test_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Описание вопроса'),
        ),
        migrations.AlterField(
            model_name='question',
            name='question_type',
            field=models.CharField(choices=[('radio', 'Один правильный ответ'), ('checkbox', 'Несколько правильных ответов'), ('input', 'Ввод текста')], default='checkbox', max_length=200, verbose_name='Тип вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Название теста'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='name',
            field=models.CharField(max_length=200),
        ),
    ]
