# Generated by Django 5.0.9 on 2025-05-11 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_alter_question_label_alter_question_question_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='points',
            field=models.IntegerField(default=1, verbose_name='Количество баллов за вопрос'),
        ),
        migrations.AddField(
            model_name='test',
            name='time_limit',
            field=models.IntegerField(default=None, null=True, verbose_name='Время на ответ в секундах'),
        ),
        migrations.AlterField(
            model_name='question',
            name='label',
            field=models.CharField(verbose_name='Описание вопроса'),
        ),
        migrations.AlterField(
            model_name='test',
            name='label',
            field=models.CharField(verbose_name='Название теста'),
        ),
    ]
