# Generated by Django 4.1.13 on 2024-09-17 07:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tests', '0003_test_label'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='correct_variants',
            field=models.ManyToManyField(related_name='correct_variants', to='tests.variant', verbose_name='Список правильных ответов'),
        ),
        migrations.AlterField(
            model_name='question',
            name='variants',
            field=models.ManyToManyField(to='tests.variant', verbose_name='Список ответов'),
        ),
        migrations.AlterField(
            model_name='test',
            name='questions_list',
            field=models.ManyToManyField(to='tests.question', verbose_name='Список вопросов'),
        ),
    ]
