# Generated by Django 4.1.13 on 2024-09-17 07:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_catalog_child'),
        ('tests', '0004_question_correct_variants_alter_question_variants_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='test',
            name='catalogs',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='categories.catalog', verbose_name='ААА'),
        ),
    ]
