# Generated by Django 4.1.13 on 2024-09-17 07:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_catalog_child'),
        ('tests', '0005_test_catalogs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='test',
            name='catalogs',
        ),
        migrations.AddField(
            model_name='test',
            name='catalogs',
            field=models.ManyToManyField(to='categories.catalog', verbose_name='ААА'),
        ),
    ]
