# Generated by Django 4.1.13 on 2024-09-17 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_catalog_child'),
        ('tests', '0006_remove_test_catalogs_test_catalogs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='test',
            name='catalogs',
            field=models.ManyToManyField(related_name='tests', to='categories.catalog', verbose_name='ААА'),
        ),
    ]
