# Generated by Django 5.1.3 on 2024-12-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlases', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст атласа'),
        ),
    ]
