# Generated by Django 4.1.13 on 2024-12-24 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlases', '0002_atlas_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas',
            name='description',
            field=models.CharField(default='', max_length=1000, verbose_name='Текст атласа'),
        ),
    ]
