# Generated by Django 5.1.3 on 2025-01-12 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlases', '0002_atlas_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atlas',
            name='label',
            field=models.CharField(max_length=200, verbose_name='Название файла'),
        ),
    ]
