# Generated by Django 4.1.13 on 2025-04-28 05:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('atlases', '0003_alter_atlas_description'),
        ('atlases', '0003_alter_atlas_label'),
    ]

    operations = [
    ]
