# Generated by Django 4.1.13 on 2025-04-28 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atlases', '0004_merge_20250428_1041'),
    ]

    operations = [
        migrations.AddField(
            model_name='atlas',
            name='tooltips',
            field=models.JSONField(default={}, verbose_name='Координаты подсказок'),
        ),
    ]
