# Generated by Django 4.1.13 on 2024-09-17 18:25

from django.conf import settings
import django.contrib.auth.models
import django.contrib.auth.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tests', '0001_initial'),
        ('articles', '0001_initial'),
        ('categories', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('username', models.CharField(error_messages={'unique': 'A user with that username already exists.'}, help_text='Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.', max_length=150, unique=True, validators=[django.contrib.auth.validators.UnicodeUsernameValidator()], verbose_name='username')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='email address')),
                ('is_staff', models.BooleanField(default=False, help_text='Designates whether the user can log into this admin site.', verbose_name='staff status')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'db_table': 'auth_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='TestUserRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_completed', models.BooleanField(default=False, verbose_name='Тест пройден?')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Тест в избранном?')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='test_user_id', to='tests.test', verbose_name='Тест')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_test_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Тест',
                'verbose_name_plural': 'Тесты',
                'db_table': 'tests_user',
            },
        ),
        migrations.CreateModel(
            name='QuestionUserRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Вопрос в избранном?')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qu_user_id', to='tests.question', verbose_name='Вопрос')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_qu_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопросы',
                'db_table': 'question_user',
            },
        ),
        migrations.CreateModel(
            name='CatalogUserRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Каталог в избранном?')),
                ('catalog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cat_user_id', to='categories.catalog', verbose_name='Каталог')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_cat_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Каталог',
                'verbose_name_plural': 'Каталоги',
                'db_table': 'catalog_user',
            },
        ),
        migrations.CreateModel(
            name='ArticleUserRel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_favorite', models.BooleanField(default=False, verbose_name='Статья в избранном?')),
                ('article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ar_user_id', to='articles.article', verbose_name='Статья')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_ar_id', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'db_table': 'articles_user',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_questions',
            field=models.ManyToManyField(related_name='user_questions', through='users.QuestionUserRel', to='tests.question', verbose_name='Список избранных вопросов'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorite_tests',
            field=models.ManyToManyField(related_name='user_tests', through='users.TestUserRel', to='tests.test', verbose_name='Список избранных тестов'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_articles',
            field=models.ManyToManyField(blank=True, related_name='articles', through='users.ArticleUserRel', to='articles.article', verbose_name='Список избранных статей'),
        ),
        migrations.AddField(
            model_name='user',
            name='favorites_catalogs',
            field=models.ManyToManyField(blank=True, related_name='catalogs', through='users.CatalogUserRel', to='categories.catalog', verbose_name='Список избранных тем'),
        ),
        migrations.AddField(
            model_name='user',
            name='groups',
            field=models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups'),
        ),
        migrations.AddField(
            model_name='user',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
    ]
