# Generated by Django 5.1.3 on 2024-11-14 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_photo_url',
            field=models.URLField(blank=True, null=True, verbose_name='Ссылка на аватар пользователя'),
        ),
    ]
