# Generated by Django 5.1.3 on 2025-01-10 17:41

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_user_telegram_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='testuserrel',
            name='last_try',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='Дата последней попытки'),
            preserve_default=False,
        ),
    ]
