# Generated by Django 4.2.11 on 2024-05-16 08:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_news'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='news',
            options={'verbose_name': 'Рассылка', 'verbose_name_plural': 'Рассылка'},
        ),
    ]
