# Generated by Django 5.1.3 on 2025-01-13 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_testuserrel_last_try'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_telegram_photo_file_id',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Последний файл ID аватара пользователя'),
        ),
    ]
