# Generated by Django 4.1.13 on 2024-09-17 09:44

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0003_alter_catalog_child'),
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.CharField(default=uuid.uuid4, max_length=20, primary_key=True, serialize=False)),
                ('label', models.CharField(max_length=50, verbose_name='Название файла')),
                ('article_file', models.FileField(upload_to='', verbose_name='Файл статьи')),
                ('catalogs', models.ManyToManyField(related_name='articles', to='categories.catalog', verbose_name='Принадлежит каталогу')),
            ],
        ),
    ]
