# Generated by Django 4.1.13 on 2024-09-17 10:32

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('categories', '0003_alter_catalog_child'),
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_file',
            field=models.FileField(upload_to='articles_storage', verbose_name='Файл статьи'),
        ),
        migrations.AlterField(
            model_name='article',
            name='catalogs',
            field=models.ManyToManyField(blank=True, related_name='articles', to='categories.catalog', verbose_name='Принадлежит каталогу'),
        ),
        migrations.AlterField(
            model_name='article',
            name='id',
            field=models.CharField(default=uuid.uuid4, max_length=100, primary_key=True, serialize=False),
        ),
    ]
