# Generated by Django 5.1.3 on 2024-12-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_photo',
            field=models.ImageField(blank=True, upload_to='articles_storage', verbose_name='Фотография статьи'),
        ),
    ]
