# Generated by Django 4.1.13 on 2024-09-13 08:59

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('child_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.category')),
                ('parent_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='categories.category')),
            ],
        ),
    ]
